/*          <!--QUESTIONS GENERATED BY FCC JAVASCRIPT COURSE-->
 * Find the Longest Word in a String
 * Return the length of the longest word in the provided sentence.
 * Your response should be a number.
 */

function longestWord(str){
    /**
     * Takes String Input
     * Use Math function to choose the word with max character count 
     * split the string to an array of characters using split function
     * map the word 
     * Output final characters in longest word
    */ 
    return Math.max(...str.split(" ").map(word => word.length))
}
console.log(longestWord("I must be a dedicated programmer"))

